exceptions.py

::: aapp2face.lib.exceptions
    options:
      members_order: source
